# Generated by Django 5.1.2 on 2024-10-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('nation', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('potential', models.IntegerField()),
                ('mood', models.IntegerField()),
                ('player_image', models.ImageField(blank=True, null=True, upload_to='player_images/')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_agency.team')),
            ],
        ),
    ]
